source: content
paths:
  data: _data
  collections: ''
  layouts: _includes/layouts
  static: public
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  pagina's:
    path: ''
    output: true
    filter:
      base: strict
      include: []
      exclude:
        - content/_schemas/
        - content/_data/
        - content/_includes/
    description: ''
    icon: web_asset
    singular_name: Pagina
    singular_key: pagina
    _editables: {}
    _inputs:
      title:
        type: auto
        label: Naam van de pagina
        cascade: true
    _select_data: {}
    _structures: {}
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: content/_schemas/page.liquid
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        icon: notes
_inputs:
  style:
    label: Opmaak
  style.background:
    type: object
    label: Achtergrond
  eleventyNavigation:
    type: object
    label: Navigatieinstellingen
  eleventyNavigation.parent:
    type: text
    label: In welk submenu?
    comment: Gebruik de navigatienaam van een andere pagina.
  eleventyNavigation.key:
    type: text
    label: Navigatienaam
    comment: Vaak hetzelfde als de paginanaam. Gebruik deze naam om te refereren naar submenu's.
  eleventyNavigation.title:
    type: text
    label: Naam in navigatiebalk
    comment: Als je dit leeg laat, wordt de navigatienaam getoond
  eleventyNavigation.url:
    type: url
    label: Link
  eleventyNavigation.order:
    type: number
    label: Volgorde
    comment: Lager cijfer betekent eerder in de navigatiebalk
    options:
      step: 1.0
  id:
    type: auto
    instance_value: UUID
    hidden: true
    cascade: true
  layout:
    type: auto
    hidden: true
    cascade: true
  permalink:
    type: auto
    hidden: true
    cascade: true
  _schema:
    type: auto
    hidden: true
    cascade: true
  meta:
    type: object
    label: Metadata
  meta.title:
    label: SEO-metatitel
    type: text
  meta.description:
    label: SEO-metabeschrijving
    type: textarea
  meta.image:
    label: Linkpreview
    type: image
    comment: Als je dit leeg laat, wordt de standaard linkpreview van CKX getoond.
    options:
      allowed_sources:
        - ckx-website
  content_blocks:
    type: auto
    label: Paginainhoud
    cascade: true
_select_data: {}
_structures: {}
_editables:
  content:
    allowed_sources:
      - mijn-bedrijf
data_config:
  contactInfo: true
timezone: Europe/Brussels
